### ISSUE TITLE
Performance audit

### ISSUE THREAD

**Issue by SamaraFellaDina** [vsheo/performance-audit#1]
> * hi! sorry ik had een drukke dag. Ik ben je niet vergeten!✨
 > * [hier kan je de documentatie vinden.](https://github.com/vsheo/performance-audit/wiki/Performance-Audit)

![](https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExbnZxN3V4NDZlZXFmZGhqeDhiZzMxNDlneGRwcjBwNGdhMnB2M3BtOSZlcD12MV9naWZzX3RyZW5kaW5nJmN0PWc/tHIRLHtNwxpjIFqPdV/200w.webp)

# algemeen
Hier zet ik even wat algemene notaties voor jullie alle drie neer. Handige dingen die goed zijn om mee te nemen die mij opvielen.

**Werk semantisch**! als je naar deze sites kijkt, zie je vaak dingen als veel `css`. Dingen als:
* veel `div` elementen, waardoor er veel classes ontstaat  
  * dit zorgt ervoor dat de sheets veel langer worden dan hoort. Werk dus gestructureerd. Doen jullie vast wel, maar nu zie je waarom het dus zo belangrijk is <3
  * ik had toevallig gisteren een artikel gevonden hoe je het zou kunnen [structureren](https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Styling_basics/Organizing#create_logical_sections_in_your_stylesheet). Erg handig :) 
* Gebruik custom properties. Zijn we net niet erg op in gegaan. Maar ook zooo handig, dan heb je een plek waar alles staat. 
* ook wat viresh zei, was erg goed. Als je selectors hebt die allemaal dezelfde property gebruiken, kan je ze ook samenvoegen

_in plaats van dit:_
``` css
h1 {
background-color: #000000;
}
h2 {
background-color: #000000;
}
```
_doe je dit:_
```css
h1, h2 {
background-color: #000000;
}
```  
* op heel veel sites zie je dat dingen worden geëxporteerd van externe sites. dingen van Google bijvoorbeeld of bijvoorbeeld afbeeldingen
  * dit kan er op komen dat de laadtijd dus ook langer word. Dus je zou dan kunnen kijken wat nou _echt_ geïmporteerd kan worden en wat je dus lokaal kan laten staan. 

# [De Koffie Salon](https://dekoffiesalon.nl/)
* **drie `css` sheets...** heel interessant. Heb medelijden met de vorige developer. Echt niet nadoen. 
* Ik vraag me inderdaad af of het `js` bestand nodig is. Het is een redelijk simpele site. Ik vind het interessant dat ze er alsnog een spelletje hebben van weten te maken. De homepagina kan zeker veeeel makkelijker. 
* Ze gebruiken zoveel `!important` elementen. Dat is dus ook waarom ik over semantische html begon. Dan hoef je dit soort dingen niet te doen, en drie sheets te maken. Ik had hierboven al aangegeven hoe je voor jezelf een mooie css structuur kan creëren. Daar kon de vorige developer ook nog wat van leren 🥲
* Er worden een aantal instagram foto's ingeladen, deze hebben een wait period. als je dit soort dingen wilt voorkomen, kan het helpen om dit soort dingen lokaal te hebben staan en niet afhankelijk te zijn van een externe server lijkt mij. 
* wij hebben het ook gehad over waarom het beter is om met selectors te werken. er zijn namelijk talloze voorbeelden van frontenters die alleen met `div` elementen werken en daarna een `class` er aan toevoegen. Deze site is er helaas ook een slachtoffer van. Als je van te voren de selectors goed stijl, scheelt het heel veel classes. en kan de site sneller laden

* hier ging ik nog het meeste stuk om:
```css
@font-face {
    font-family: 'Roboto';
    font-style: normal;
    font-weight: 300;
    font-stretch: 100%;
    src: url(https://fonts.gstatic.com/s/roboto/v47/KFO7CnqEu92Fr1ME7kSn66aGLdTylUAMa3GUBHMdazTgWw.woff2) format('woff2');
    unicode-range: U + 0460-052F, U + 1C80-1C8A, U + 20B4, U + 2DE0-2DFF, U + A640-A69F, U + FE2E-FE2F;
}
```

een `@font-face`, om dan toch een url op te halen ☠️ Beter om dit soort dingen lokaal te hebben staan, zodat hiervoor geen wait en daardoor laadtijd ontstaan. 

# Lekker bezig!
* je had het erg goed uitgelegd en had zelf al goed door wat er allemaal mis ging op de site. Ik vond ook dat je goede opmerkingen maakte over hoe je de css kan structureren om zo lange sheets te voorkomen. Erg leuk
* ik zou de volgende keer even je documentatie goed opmaken. ik zag namelijk dat je soms code benoemt in de documentatie. Hiervoor zijn voor markdown speciale elementen waardoor de tekst netter word opgemaakt. Misschien even in verdiepen om zo je uitleg net wat duidelijker te hebben 

![](https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExbzB6aTZxNnE3cmxuOHVzaTVocXZ5dmxycTl6OHB1OGRkdHhwanNjMSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/5xaOcLGvzHxDKjufnLW/200w.webp
)
Als je nog vragen/opmerkingen hebt, hoor ik het graag!
> Nu ga ik naar bed 🛏️
